export const createMockedTab = ({ id, title }) => ({
  id,
  index: 1,
  windowId: 1,
  highlighted: false,
  active: false,
  attention: false,
  pinned: true,
  status: "complete",
  hidden: false,
  discarded: false,
  incognito: false,
  width: 1508,
  height: 933,
  lastAccessed: 1653338892342,
  audible: false,
  mutedInfo: { muted: false },
  isInReaderMode: false,
  sharingState: { camera: false, microphone: false },
  successorTabId: -1,
  cookieStoreId: "firefox-default",
  url: "https://mail.yahoo.com/d/folders/1?reason=invalid_crumb",
  title,
  favIconUrl: "https://mail.yahoo.com/favicon.ico",
});
